backend:
  name: git-gateway

publish_mode: editorial_workflow
media_folder: 'content/media/uploads'

editor:
  # Maybe enable this later if we add a custom preview
  preview: false

collections:
  - name: case
    label: Case
    folder: '/content/case'
    create: true
    fields:
      - { name: 'title', label: 'Title', widget: 'string' }
      - { name: 'excerpt', label: 'Excerpt', widget: 'text' }
      - { name: 'client', label: 'Kund', widget: 'string' }
      - {
          name: 'date',
          label: 'Publish date',
          widget: 'datetime',
          format: 'Y-MM-DDThh:mm:ssZ',
        }
      - {
          name: 'image',
          label: 'Featured image',
          widget: 'image',
          required: false,
        }
      - { name: 'tags', label: 'Tags', widget: 'list', required: false }
      - { name: 'body', label: 'Body', widget: 'markdown' }

  - name: 'articles'
    label: 'Articles'
    folder: '/content/aktuellt'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    fields:
      - { name: 'title', label: 'Title', widget: 'string' }
      - { name: 'excerpt', label: 'Excerpt', widget: 'text' }
      - { name: 'date', label: 'Publish date', widget: 'datetime' }
      - { name: 'tags', label: 'Tags', widget: 'list', required: false }
      - { name: 'body', label: 'Body', widget: 'markdown' }
